#!/usr/bin/env bash
#
# src/lib/config.sh - Configuration load / save / validate / edit.
#
# The installer persists all of its decisions in two files:
#   * ${CALAGOPUS_CONFIG_FILE}  - installer's own settings (channel, mode, etc.)
#   * ${CALAGOPUS_STATE_FILE}   - what is actually installed on this host
# Both are simple KEY='value' shell snippets so they are safe to `source` and
# trivially diffable. The in-memory representation is the CFG associative
# array declared in common.sh.
#
# Why not YAML/JSON for the primary state? Because we want zero runtime
# dependencies (no yq/jq required to read your own config). We still offer
# export/import helpers that emit JSON for tooling interop (see config_export).

if [ -n "${CALAGOPUS_LIB_CONFIG:-}" ]; then return 0; fi
CALAGOPUS_LIB_CONFIG=1

# -----------------------------------------------------------------------------
# Low-level KEY='value' file <-> CFG sync
# -----------------------------------------------------------------------------

# Load a KEY='value' file into CFG. Missing file is not an error (first run).
config_load_file() {
	local file="$1" key val
	[ -f "$file" ] || return 0
	while IFS='=' read -r key val; do
		# skip comments / blanks
		case "$key" in ''|\#*) continue ;; esac
		# strip surrounding quotes
		val="${val#\'}"; val="${val%\'}"
		val="${val#\"}"; val="${val%\"}"
		CFG["$key"]="$val"
	done <"$file"
}

# Persist a single KEY='value' file from the given list of keys.
config_save_file() {
	local file="$1"; shift
	local dir; dir="$(dirname "$file")"
	mkdir -p "$dir" 2>/dev/null || true
	local tmp; tmp="${file}.tmp.$$"
	{
		printf '# Generated by Calagopus Installer on %s\n' "$(date '+%Y-%m-%dT%H:%M:%S%z')"
		printf '# DO NOT edit by hand unless you know what you are doing.\n'
		local k v
		for k in "$@"; do
			v="${CFG[$k]:-}"
			# Quote single quotes inside values.
			v="${v//\'/\'\\\'\'}"
			printf "%s='%s'\n" "$k" "$v"
		done
	} >"$tmp"
	chmod 0600 "$tmp"
	mv "$tmp" "$file"
	chmod 0600 "$file"
}

# Keys that live in the installer config file (user-facing settings).
CALAGOPUS_CONFIG_KEYS=(
	DEPLOY_MODE RELEASE_CHANNEL INSTALL_TARGET
	PANEL_FQDN PANEL_PORT PANEL_IMAGE VARIANT
	WINGS_FQDN WINGS_PORT WINGS_IMAGE
	DB_HOST DB_PORT DB_NAME DB_USER DB_REMOTE
	REDIS_HOST REDIS_PORT REDIS_MODE
	PROXY_ENGINE SSL_PROVIDER
	FIREWALL_ENGINE
	BACKUP_SCHEDULE BACKUP_RETENTION
)

# Keys that live in the state file (what is installed).
CALAGOPUS_STATE_KEYS=(
	INSTALLED_PANEL INSTALLED_PANEL_VERSION INSTALLED_PANEL_MODE
	INSTALLED_WINGS  INSTALLED_WINGS_VERSION  INSTALLED_WINGS_MODE
	INSTALLED_DB INSTALLED_REDIS INSTALLED_DOCKER INSTALLED_PROXY
	INSTALLED_SSL INSTALLED_FIREWALL
	INSTALLED_AT LAST_UPGRADED_AT
)

config_load() {
	config_load_file "${CALAGOPUS_CONFIG_FILE}"
	config_load_file "${CALAGOPUS_STATE_FILE}"
}

# Save installer config + state atomically.
config_save() {
	config_save_file "${CALAGOPUS_CONFIG_FILE}" "${CALAGOPUS_CONFIG_KEYS[@]}"
	config_save_file "${CALAGOPUS_STATE_FILE}"  "${CALAGOPUS_STATE_KEYS[@]}"
}

# -----------------------------------------------------------------------------
# Field accessors with defaults (keeps call sites concise)
# -----------------------------------------------------------------------------
config_get() { printf '%s' "${CFG[$1]:-}"; }
config_set() { CFG["$1"]="$2"; }
config_get_default() { printf '%s' "${CFG[$1]:-$2}"; }

# True if the named component is recorded as installed in state.
config_is_installed() {
	local comp="$1"
	if [ -n "${CFG["INSTALLED_${comp}"]:-}" ]; then common_is_yes "${CFG["INSTALLED_${comp}"]}"; else return 1; fi
}

config_mark_installed() {
	local comp="$1" val="${2:-yes}"
	CFG["INSTALLED_${comp}"]="$val"
	CFG["INSTALLED_AT"]="$(date '+%Y-%m-%dT%H:%M:%S%z')"
	config_save
}
config_mark_uninstalled() { CFG["INSTALLED_${1}"]="no"; config_save; }

# -----------------------------------------------------------------------------
# Validation - fail fast on obviously bad config before touching the system.
# -----------------------------------------------------------------------------
config_validate() {
	local errors=0
	local fqdn_re='^([a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?\.)+[a-zA-Z]{2,}$'

	# FQDNs only required for panel / proxy with SSL.
	# Allow 'localhost' and bare hostnames (no dot) for homelab/dev use.
	if [ -n "${CFG[PANEL_FQDN]:-}" ]; then
		case "${CFG[PANEL_FQDN]}" in
			localhost) ;;  # always valid
			*)
				local fqdn_re='^([a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?\.)*[a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?$'
				if ! [[ "${CFG[PANEL_FQDN]}" =~ $fqdn_re ]]; then
					log_error "PANEL_FQDN '${CFG[PANEL_FQDN]}' is not a valid hostname"
					errors=$((errors+1))
				fi
				;;
		esac
	fi

	# Release channel must be one of the known set.
	case "${CFG[RELEASE_CHANNEL]:-stable}" in
		stable|beta|nightly) ;;
		*) log_error "RELEASE_CHANNEL must be stable|beta|nightly"; errors=$((errors+1)) ;;
	esac

	# Deploy mode + target combinations.
	case "${CFG[DEPLOY_MODE]:-docker}" in docker|native) ;; *) errors=$((errors+1)); log_error "DEPLOY_MODE invalid";; esac
	case "${CFG[INSTALL_TARGET]:-}" in panel|wings|full) ;; "") ;; *) log_error "INSTALL_TARGET invalid"; errors=$((errors+1));; esac

	# DB port numeric
	[ "${CFG[DB_PORT]:-5432}" -gt 0 ] 2>/dev/null || { log_error "DB_PORT invalid"; errors=$((errors+1)); }

	# Encryption key must be set whenever panel is installed.
	if config_is_installed PANEL && [ -z "${CFG[APP_ENCRYPTION_KEY]:-}" ]; then
		log_error "APP_ENCRYPTION_KEY missing while panel installed"; errors=$((errors+1))
	fi

	return "$errors"
}

# -----------------------------------------------------------------------------
# Safe edit + import/export
# -----------------------------------------------------------------------------

# Backup a file before an external editor / sed mutates it. Returns backup path.
config_backup_file() {
	local f="$1" bak
	[ -f "$f" ] || return 0
	bak="${f}.bak.$(date +%s)"
	cp -a "$f" "$bak"
	printf '%s' "$bak"
}

# Export the current CFG to JSON on stdout (requires no jq - hand-rolled).
config_export_json() {
	local k v first=1
	printf '{'
	for k in "${CALAGOPUS_CONFIG_KEYS[@]}" "${CALAGOPUS_STATE_KEYS[@]}"; do
		v="${CFG[$k]:-}"
		# naive JSON string escaping
		v="${v//\\/\\\\}"; v="${v//\"/\\\"}"; v="${v//$'\n'/\\n}"
		[ "$first" -eq 1 ] || printf ','
		printf '"%s":"%s"' "$k" "$v"
		first=0
	done
	# include secret-bearing keys (masked) for audit exports
	# (single key today; kept as a loop so adding more is trivial)
	local sk v
	sk="APP_ENCRYPTION_KEY"
	v="${CFG[$sk]:-}"
	[ -n "$v" ] && v="**REDACTED**"
	printf ',"%s":"%s"' "$sk" "$v"
	printf '}\n'
}

# Import minimal KEY=VALUE pairs from a file (one per line, optional quotes).
config_import_env() {
	local file="$1"
	[ -f "$file" ] || { log_error "import file not found: $file"; return 1; }
	config_load_file "$file"
	config_save
	log_ok "imported configuration from $file"
}
